### ISSUE TITLE
食材や料理名から主食・副菜などを分類できるようにする

### ISSUE THREAD

**Issue by Yokomi422** [ut-code/menu#114]
[spoonacular recipe and food API](https://spoonacular.com/food-api)などを使って

**Comment by bvv-1** [comment]
今考えている方針は、手動でのラベリングを楽にする方針で、単純な画像分類タスク（文字情報も出す）を手助けするツールを導入したい気持ち
https://github.com/opencv/cvat

**Comment by bvv-1** [comment]
とはいえ、この手動ラベリングは最終手段なので、基本的にはルールベースでつけたい
例：キーワードに「うどん」が入っていたらすべて主食
