### ISSUE TITLE
質問への回答状況をいかに管理するか

### ISSUE THREAD

**Issue by bvv-1** [ut-code/menu#14]
質問への回答状況はpropsで渡すことになりそう？
useStateであるselectedを作成して、App.tsxがすべての親コンポーネントとなって管理

cookieは大変なことになるので、前回はlocalStrageを使ったが、今回はどうしましょう？

**Comment by chvmvd** [comment]
localStorage は使い方はとても簡単(5 分もあれば、やりたいことができる)なので、とりあえず localStorage 使うのはありかもですね。

**Comment by bvv-1** [comment]
ですよね
（実は実装で詰まっているんですが…）

**Comment by chvmvd** [comment]
もしかしたら、誤解があるかもなのですが、(知ってたらごめんなさい。)localStorage ってローカルに保存するってことではなく、ローカルに保存はしているのですが、localStorage という一つの機能です。
フロント側に一行書くだけで保存はできます。以下の記事が参考になるかもです。
[https://qiita.com/masuda-sankosc/items/cff6131efd6e1b5138e6](https://qiita.com/masuda-sankosc/items/cff6131efd6e1b5138e6)

**Comment by chvmvd** [comment]
オブジェクトなら、以下のようにJSON にして保存できます。
[https://qiita.com/terufumi1122/items/6ddd9c520a9d0a19896a](https://qiita.com/terufumi1122/items/6ddd9c520a9d0a19896a)

**Comment by bvv-1** [comment]
あっさり出来ました、ありがとう！！！
（型関係でずっとやらかしてましたが、alert(typeof(...))で調べたら行けました）
