### ISSUE TITLE
「だるめし」要素を追加する

### ISSUE THREAD

**Issue by bvv-1** [ut-code/menu#160]
- だるめし度を数値化して、Recommendationアルゴリズムに使用するなど、自由なアイディアで
  - 評価値の設計が鍵

**Comment by Futaba-rgb** [comment]
Dialogコンポーネントのデザインはもう少し工夫できそう
![ccb8d838e4a89b322b1764937c5ecf0e](https://github.com/ut-code/menu/assets/104970783/b94e9cbe-b082-4764-99e0-1677ef02775f)
