### ISSUE TITLE
[フロントエンド] HowToのNextボタンの改良

### ISSUE THREAD

**Issue by bvv-1** [ut-code/menu#186]
Starterチケット

[Figma](https://www.figma.com/file/yM4TNeiIe9gt7g2Y2a9eCu/ui?type=design&node-id=94-33&mode=design&t=xf8yMumJgYusTfqi-0) に従い、Nextの色を黄色くして、最後はStartにする

**Comment by bvv-1** [comment]
@SatohiroToko このissue、内容変わるかもしれないです、すみません！

**Comment by SatohiroToko** [comment]
返信遅くなってすみません。
了解しました！
