### ISSUE TITLE
画像をpublic/assetsに移動する

### ISSUE THREAD

**Issue by bvv-1** [ut-code/menu#208]
- public推進派の人がいたので

**Comment by chvmvd** [comment]
推進したいというよりは、統一するのなら、理由を添えてくれた方が納得しやすいだろうなと思っただけです。こういうのは、メリット、デメリットがあるのでチーム内で合意をとることが重要なのではないかという感じです。

**Comment by chvmvd** [comment]
`public`に入れた場合は、おそらくimportできない気がします。
それと、URLの解決方法がこれに関しては一番重要な話なのかなと思います。

**Comment by bvv-1** [comment]
とりあえず、CSSからアクセスする場合は例外として処理することにしましょう。
