### ISSUE TITLE
ページ遷移の時に無駄な読み込みが発生している

### ISSUE THREAD

**Issue by chvmvd** [ut-code/menu#38]
次のように書くと、ページがリロードされてしまうので、無駄な読み込みが発生する。
```tsx
<a href="/home">戻る</a>
```

https://user-images.githubusercontent.com/104971044/220141363-b86a6f28-d0b7-40f7-8fcc-5c7d43ff37ca.mov

React Router 風に次のように書くと、無駄な読み込みが発生しない。
```tsx
import { Link } from "react-router-dom"
...
<Link to={"/home"}>戻る</Link>
```

https://user-images.githubusercontent.com/104971044/220141434-ce3ee716-ae1c-4dd9-9f44-de7e2c45081e.mov

**Comment by chvmvd** [comment]
たまたま見つけたので、Issue にしておきました。
React Router 使うときの遷移は、このようにした方が良いらしいです。

**Comment by chvmvd** [comment]
`window.location.href = "/result"` とかも Navigate とかに変えた方が良さそうです。

**Comment by bvv-1** [comment]
直しました！ありがとう〜😊

**Comment by chvmvd** [comment]
ありがとうございます！
