### ISSUE TITLE
`cors` の設定方法

### ISSUE THREAD

**Issue by chvmvd** [ut-code/menu#42]
https://github.com/ut-code/menu/blob/8a6b1d52b1849e0059b00c2f2ce9b0e2855a3fa6/backend/server.ts#L13

ここを次のように設定すると、設定できるらしいです。あまりよくはわかってませんが。デプロイ先以外からバックエンドにアクセスできなくなります。
バックエンドが動いているかをローカルからテストできなくなる気がするので、今はやらなくても良い気がします。必要になったときで。
```js
app.use(cors({ origin: process.env["WEB_ORIGIN"] }))
```

**Comment by bvv-1** [comment]
たしかに見覚えがある書き方ですね、そういう意味があったのか…

**Comment by chvmvd** [comment]
そういえば、タイピングゲームの方にも書いてありましたね。
