### ISSUE TITLE
デプロイ先のrenderでの不具合

### ISSUE THREAD

**Issue by bvv-1** [ut-code/menu#62]
- [x] トランジションが反映されていない
- [x] src=/src/...ってなってる箇所の画像がdistにない
- [x] 検索結果が表示されない

**Comment by chvmvd** [comment]
あれま…

**Comment by chvmvd** [comment]
トランジションは反映されてる？

**Comment by bvv-1** [comment]
検索結果はいけてました
トランジションはいつの間にか手元でも動かなくなってます…

**Comment by bvv-1** [comment]
2つ目は/publicに移動すればいいだけなので大丈夫そうです

**Comment by chvmvd** [comment]
良かった。
チェックボックスってそうやったら、使えるんだ！なるほど。

**Comment by bvv-1** [comment]
直せました
