### ISSUE TITLE
見た目：レシピ名や説明が短いと幅が狭くなる

### ISSUE THREAD

**Issue by bvv-1** [ut-code/menu#63]
![image](https://user-images.githubusercontent.com/53532178/222438190-a23d4f1e-fb47-4d55-8587-b5fd175bf678.png)

**Comment by Futaba-rgb** [comment]
imageのwidthを100%にすれば横幅は揃いそうだけどたまに縦幅が大きすぎたりするのが気になる。
だからと言って縦幅を指定すると画像の元々の縦横比があるので↑のようになってしまう。。。。
どのレイアウトの方がマシか、相談させて欲しいです。
